[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
feyman = "6HvfTD5hFak27YUkfGeQWMfbkoGFF1P4cGxtv2Wj6oJK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/manhtb/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
